# Clears costmap layer within reset_distance around a specified pose
# Since the base costmap layer does not suport this, it is meant to be used on specific layers

float32 reset_distance
geometry_msgs/PoseStamped pose
---
bool status